language: python
python:
    - "2.7"
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install texinfo
    - git clone --depth=1 git://git.sv.gnu.org/libjit.git
    - cd libjit && ./auto_gen.sh
    - ./configure --prefix=/usr && make && sudo make install
    - cd -
script:
    - python setup.py build
    - python setup.py test

